[workspace]
members = ["crates/minidx-core"]
resolver = "2"

[workspace.dependencies]
num-traits = { version = "0.2.17", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }